/* ============================================================
   data.js — Recipe database
   Add recipes through the admin panel at /admin/
   This file is auto-generated — do not edit manually
   ============================================================ */

const RECIPES = [
  {
    id: 'chermoula-grilled-fish',
    title: 'Chermoula Grilled Fish',
    description: 'North African herb and spice marinade on branzino or any firm white fish',
    category: ['Dinner'],
    cuisine: 'North African',
    protein: 'Fish',
    methods: ['Grill', 'Oven', 'Stovetop'],
    time: '30–60 min',
    net_carbs: '~3g',
    protein_g: '~38g',
    serves: 2,
    skill: 'Moderate',
    yeast_flag: true,
    yeast_note: 'Check harissa label if using as a finishing sauce — some commercial brands contain yeast extract.',
    ingredients: [
      { qty: '2', item: 'branzino or sea bass fillets (6–8 oz each)', source: 'Asian grocery, fish market, or specialty grocery' },
      { qty: '½ cup', item: 'fresh parsley, packed' },
      { qty: '¼ cup', item: 'fresh cilantro' },
      { qty: '3', item: 'garlic cloves, minced' },
      { qty: '1½ tsp', item: 'ground cumin' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '¼ tsp', item: 'cayenne pepper' },
      { qty: '3 tbsp', item: 'extra virgin olive oil', source: 'Standard grocery or warehouse club' },
      { qty: '1', item: 'lemon, juiced' },
      { qty: '', item: 'Salt and pepper to taste' },
    ],
    substitutes: [
      { ingredient: 'Branzino / sea bass', alt: 'Any firm white fish: snapper, trout, tilapia, cod, mahi mahi, striped bass, or black sea bass. Salmon also works beautifully with chermoula.', store: 'Asian grocery, local fish market, or specialty grocery — search Google for "fish market near me"' },
      { ingredient: 'Fresh cilantro', alt: 'Not a cilantro fan? Double the parsley and add a handful of fresh mint. Still authentically North African.' },
      { ingredient: 'Extra virgin olive oil', alt: 'Avocado oil is a clean substitute with a higher smoke point — actually better for high-heat grilling.', store: 'Any standard grocery, warehouse club, or online' },
      { ingredient: 'Smoked paprika', alt: 'Regular paprika plus a pinch of cumin works in a pinch. Chipotle powder (tiny amount) also gives smoky depth.' },
    ],
    steps: {
      Grill: [
        'Blend parsley, cilantro, garlic, cumin, paprika, cayenne, olive oil, and lemon juice into a paste. Reserve 2 tbsp for serving.',
        'Score fish skin 3x on each side. Rub marinade all over including inside cuts. Marinate 30 min minimum.',
        'Heat grill to medium-high. Oil grates well. Place fish skin-side down. Cook 4–5 min until skin releases cleanly.',
        'Flip once. Cook 3–4 min until flesh is opaque. Do not move the fish until it releases on its own.',
        'Rest 2 min. Drizzle with reserved chermoula and fresh lemon. Serve immediately.',
      ],
      Oven: [
        'Preheat oven to 425°F. Line a baking sheet with foil. Blend and reserve chermoula as above.',
        'Marinate fish for at least 20 min. Place skin-side down on prepared sheet.',
        'Roast 12–15 min until flesh flakes easily. Finish 2 min under broiler for color.',
        'Drizzle reserved chermoula and squeeze of lemon. Serve from the pan.',
      ],
      Stovetop: [
        'Blend and reserve chermoula as above. Marinate fish for 20 min.',
        'Heat cast iron over high heat until smoking. Add 1 tsp oil.',
        'Place fish skin-side down. Press gently with spatula for first 30 seconds.',
        'Cook 4 min without moving. Flip, cook 2–3 min. Skin should be deep golden and crisp.',
        'Finish with reserved chermoula and lemon off heat.',
      ],
    },
    carb_breakdown: [
      { item: 'Chermoula herbs and spices', carbs: '1.5g' },
      { item: 'Lemon juice', carbs: '1.0g' },
      { item: 'Garlic (3 cloves)', carbs: '0.5g' },
      { item: 'Fish / olive oil', carbs: '0g' },
    ],
    notes: [
      'Plateau tip: use 1 tbsp measured olive oil in the marinade — the fish itself provides natural fat.',
      'Chermoula keeps refrigerated 5 days — make a double batch and use as a salad dressing mid-week.',
      'Buy fish the same day you cook it for best results. Your local fish market or Asian grocery is ideal.',
      'If using harissa as a finishing sauce, check the label for yeast extract.',
    ],
    sides: ['Taktouka', 'Escalivada', 'Zaalouk', 'Arugula with lemon', 'Grilled zucchini', 'Moroccan carrot salad'],
  },
  {
    id: 'suya-skewers',
    title: 'Suya Skewers',
    description: 'West African spiced beef or chicken skewers with a groundnut rub',
    category: ['Dinner'],
    cuisine: 'West African',
    protein: 'Beef',
    methods: ['Grill', 'Broil'],
    time: '30–60 min',
    net_carbs: '~2g',
    protein_g: '~42g',
    serves: 2,
    skill: 'Easy',
    yeast_flag: false,
    ingredients: [
      { qty: '1 lb', item: 'beef sirloin or chicken breast, cut into 1-inch strips', source: 'Warehouse club or standard grocery' },
      { qty: '3 tbsp', item: 'roasted groundnut powder (unsalted peanuts, blended fine)' },
      { qty: '1 tsp', item: 'smoked paprika' },
      { qty: '1 tsp', item: 'ground ginger' },
      { qty: '1 tsp', item: 'garlic powder' },
      { qty: '½ tsp', item: 'cayenne pepper' },
      { qty: '½ tsp', item: 'onion powder' },
      { qty: '1 tbsp', item: 'neutral oil (avocado or groundnut)' },
      { qty: '', item: 'Salt to taste' },
    ],
    substitutes: [
      { ingredient: 'Roasted groundnut powder', alt: 'Unsalted peanut butter (1 tbsp) thinned with a little water works as a quick substitute. Or simply omit and double the paprika for a drier rub.', store: 'Standard grocery or natural grocery' },
      { ingredient: 'Beef sirloin', alt: 'Chicken breast, chicken thighs, or lamb work equally well. Chicken thighs are juicier and harder to overcook.' },
    ],
    steps: {
      Grill: [
        'Combine groundnut powder, paprika, ginger, garlic powder, cayenne, and onion powder. Mix well.',
        'Thread meat onto skewers. Brush lightly with oil, then coat generously with the spice rub. Rest 20 min.',
        'Grill over medium-high heat, turning every 2–3 min, for 10–12 min total until charred and cooked through.',
        'Rest 3 min before serving. Serve with sliced tomatoes and onions.',
      ],
      Broil: [
        'Prepare skewers as above. Place on a foil-lined baking sheet.',
        'Broil on high 4–5 min per side, watching closely for char without burning.',
        'Rest 3 min before serving.',
      ],
    },
    carb_breakdown: [
      { item: 'Groundnut powder', carbs: '1.0g' },
      { item: 'Spices', carbs: '0.8g' },
      { item: 'Beef / oil', carbs: '0g' },
    ],
    notes: [
      'Suya spice rub can be made in bulk and stored in an airtight jar for 3 months.',
      'Traditional suya is served with raw onions, tomatoes, and shredded cabbage — all keto-friendly.',
      'For authentic flavor, use groundnut oil. Avocado oil is a clean substitute with a neutral taste.',
    ],
    sides: ['Shredded cabbage slaw', 'Sliced tomatoes and onions', 'Cauliflower dirty rice', 'Grilled zucchini'],
  },
  {
    id: 'keto-bbq-sauce',
    title: 'Keto BBQ Sauce',
    description: 'Sweet, smoky, spicy — a full-flavor rebuild using monk fruit allulose',
    category: ['Sauces'],
    cuisine: 'BBQ',
    protein: '',
    methods: ['Stovetop'],
    time: 'Under 30 min',
    net_carbs: '~2g per 2 tbsp',
    protein_g: '0g',
    serves: 16,
    skill: 'Easy',
    yeast_flag: true,
    yeast_note: 'Check Worcestershire sauce label. Lea & Perrins original is generally clean but verify your bottle. Annie\'s Worcestershire is a reliable alternative.',
    ingredients: [
      { qty: '¾ cup', item: 'no-sugar-added ketchup (Primal Kitchen)', source: 'Natural grocery or online' },
      { qty: '3 tbsp', item: 'tomato paste (no sugar added)', source: 'Standard grocery' },
      { qty: '3 tbsp', item: 'apple cider vinegar' },
      { qty: '3 tbsp', item: 'Besti brown monk fruit / allulose sweetener', source: 'Online (Amazon) or natural grocery' },
      { qty: '1 tbsp', item: 'Worcestershire sauce (verify label)', source: 'Standard grocery — verify no yeast extract' },
      { qty: '1 tbsp', item: 'hot sauce (Frank\'s or Crystal)' },
      { qty: '1 tbsp', item: 'dill relish, no sugar added' },
      { qty: '1½ tsp', item: 'smoked paprika' },
      { qty: '1 tsp', item: 'garlic powder' },
      { qty: '1 tsp', item: 'onion powder' },
      { qty: '½ tsp', item: 'black pepper' },
      { qty: '¼ tsp', item: 'cayenne pepper' },
      { qty: '½ tsp', item: 'liquid smoke (optional)', source: 'Standard grocery, spice aisle' },
    ],
    substitutes: [
      { ingredient: 'Primal Kitchen ketchup', alt: 'Any no-sugar-added ketchup works. Check the label for hidden sugars and yeast extract.', store: 'Natural grocery or online' },
      { ingredient: 'Besti brown sweetener', alt: 'Any monk fruit / allulose blend without erythritol. Avoid erythritol-based sweeteners — large amounts can cause digestive distress.' },
      { ingredient: 'Dill relish', alt: 'Finely chopped dill pickle works perfectly. Just check the label for added sugar.' },
    ],
    steps: {
      Stovetop: [
        'In a medium saucepan over medium heat, combine ketchup, tomato paste, and apple cider vinegar. Whisk until smooth.',
        'Add sweetener, Worcestershire, hot sauce, and dill relish. Whisk to incorporate.',
        'Add smoked paprika, garlic powder, onion powder, black pepper, cayenne, and liquid smoke if using. Stir well.',
        'Reduce heat to low. Simmer uncovered 15 min, stirring occasionally, until thickened. Taste and adjust.',
        'Cool completely before jarring. Refrigerate up to 3 weeks. Apply to proteins in the last 5–10 min of grilling only — allulose caramelizes faster than sugar.',
      ],
    },
    carb_breakdown: [
      { item: 'No-sugar ketchup (¾ cup)', carbs: '12g total' },
      { item: 'Tomato paste', carbs: '4g total' },
      { item: 'Dill relish', carbs: '1g total' },
      { item: 'Sweetener (Besti)', carbs: '0g' },
      { item: 'Per 2 tbsp serving (16 servings)', carbs: '~2g' },
    ],
    notes: [
      'Allulose caramelizes at lower temperatures than sugar — always apply this sauce in the final 5–10 min of grilling to avoid scorching.',
      'Doubles and freezes well in ice cube trays for single-use portions.',
      'Adjust cayenne up to ½ tsp for real heat, or reduce to ⅛ tsp for mild.',
      'The Besti brown sweetener gives molasses depth that plain monk fruit cannot — worth seeking out.',
    ],
    sides: [],
  },
  {
    id: 'escalivada',
    title: 'Escalivada',
    description: 'Catalan roasted peppers and eggplant in olive oil — a versatile keto staple',
    category: ['Sides'],
    cuisine: 'Spanish',
    protein: '',
    methods: ['Grill', 'Oven'],
    time: '30–60 min',
    net_carbs: '~5g',
    protein_g: '1g',
    serves: 4,
    skill: 'Easy',
    yeast_flag: false,
    ingredients: [
      { qty: '2', item: 'large red bell peppers' },
      { qty: '1', item: 'large eggplant' },
      { qty: '2', item: 'medium tomatoes (optional)' },
      { qty: '3 tbsp', item: 'extra virgin olive oil', source: 'Standard grocery or warehouse club' },
      { qty: '2', item: 'garlic cloves, minced' },
      { qty: '', item: 'Fresh parsley, salt, and black pepper to taste' },
    ],
    substitutes: [
      { ingredient: 'Red bell peppers', alt: 'Any color bell pepper works. Poblano peppers add a mild smokiness and are worth trying.' },
      { ingredient: 'Eggplant', alt: 'Zucchini is a quick substitute — reduce roasting time by 10 min as it cooks faster.' },
    ],
    steps: {
      Grill: [
        'Place whole peppers and eggplant directly on hot grill grates over high heat.',
        'Char on all sides, turning occasionally, until completely blackened outside and collapsed — about 15–20 min for peppers, 25–30 min for eggplant.',
        'Place in a sealed bag or covered bowl for 10 min to steam. Peel away all skin under cool running water.',
        'Tear into strips by hand. Arrange on a platter, drizzle with olive oil, scatter garlic and parsley. Season generously.',
        'Serve warm or at room temperature. Improves after a day in the refrigerator.',
      ],
      Oven: [
        'Preheat oven to 450°F. Place peppers and eggplant on a baking sheet.',
        'Roast 35–45 min, turning once halfway, until skins are blistered and vegetables are fully collapsed.',
        'Steam, peel, and finish as above.',
      ],
    },
    carb_breakdown: [
      { item: 'Bell peppers (2 large)', carbs: '8g total' },
      { item: 'Eggplant (1 large)', carbs: '8g total' },
      { item: 'Olive oil / garlic', carbs: '0.5g' },
      { item: 'Per serving (serves 4)', carbs: '~5g' },
    ],
    notes: [
      'Escalivada improves with time — make it the night before for the best flavor.',
      'Excellent alongside grilled lamb, fish, or chicken. Also works beautifully on a cheese board.',
      'The char is essential — do not try to roast without high heat. The blackened skin is what creates the smoky flavor.',
    ],
    sides: [],
  },
  {
    id: 'egg-bites',
    title: 'Egg Bites',
    description: 'Batch-prepped Sunday breakfast — 6+ flavor varieties, 5-day refrigerator life',
    category: ['Breakfast'],
    cuisine: 'Mediterranean',
    protein: 'Eggs',
    methods: ['Oven'],
    time: '30–60 min',
    net_carbs: '~2g',
    protein_g: '~12g',
    serves: 7,
    skill: 'Easy',
    yeast_flag: true,
    yeast_note: 'Verify any cured meats (sausage, bacon, ham, salami) for yeast extract on the label before use.',
    ingredients: [
      { qty: '4', item: 'large eggs' },
      { qty: '1 cup', item: 'heavy cream' },
      { qty: '¼ cup', item: 'shredded cheese (cheddar, gruyère, or manchego)' },
      { qty: '', item: 'Salt, pepper, and your choice of fillings (see notes)' },
    ],
    substitutes: [
      { ingredient: 'Heavy cream', alt: 'Full-fat coconut milk works for a dairy-free version. Half-and-half adds carbs — avoid.' },
      { ingredient: 'Cheese', alt: 'Any melting cheese works: mozzarella, provolone, feta (crumbled, not melted), or goat cheese.' },
    ],
    steps: {
      Oven: [
        'Preheat oven to 325°F. Grease a silicone egg bite mold or muffin tin well.',
        'Whisk eggs, heavy cream, cheese, salt, and pepper until fully combined and slightly frothy.',
        'Add 1 tbsp of your chosen filling to each cavity.',
        'Pour egg mixture over fillings, filling each cavity about ¾ full.',
        'Place mold in a baking dish. Add hot water to the dish until it reaches halfway up the mold sides (bain marie).',
        'Bake 25–30 min until set and slightly puffed. A toothpick should come out clean.',
        'Cool completely before refrigerating. Microwave 30 sec to reheat. Store up to 5 days.',
      ],
    },
    carb_breakdown: [
      { item: 'Eggs (4)', carbs: '1.4g total' },
      { item: 'Heavy cream (1 cup)', carbs: '6.4g total' },
      { item: 'Cheese', carbs: '0.5g total' },
      { item: 'Per bite (makes 7)', carbs: '~2g' },
    ],
    notes: [
      'Filling varieties: sausage, bacon, crab meat, smoked salmon, country ham, spinach + feta, chorizo + manchego, prosciutto + mushroom.',
      'Make 2 varieties each batch Sunday — alternate week to week to prevent boredom.',
      'The bain marie (water bath) is what keeps them creamy. Do not skip it.',
      'Freeze extras in a single layer, then bag them. Microwave from frozen 60–90 sec.',
      'Verify all cured meats for yeast extract before using as a filling.',
    ],
    sides: [],
  },
];

/* Export for use in other files */
if (typeof module !== 'undefined') module.exports = RECIPES;
